In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

In [2]:
DATABASE_URL = "postgresql://postgres:harshith123@localhost:5432/nifty100warehouse"

engine = create_engine(DATABASE_URL)

print("Connected")

Connected

In [3]:
profit_df = pd.read_sql(
    "SELECT * FROM fact_profit_loss",
    engine
)

balance_df = pd.read_sql(
    "SELECT * FROM fact_balance_sheet",
    engine
)

company_df = pd.read_sql(
    "SELECT * FROM dim_company",
    engine
)

In [4]:
latest_profit = (
    profit_df
    .sort_values("year")
    .groupby("symbol")
    .tail(1)
)

latest_balance = (
    balance_df
    .sort_values("year")
    .groupby("symbol")
    .tail(1)
)

In [5]:
peer_df = latest_profit.merge(
    latest_balance,
    on="symbol"
)

peer_df = peer_df.merge(
    company_df,
    on="symbol"
)

peer_df.head()

,symbol,year_x,sales,net_profit,year_y,equity_capital,reserves,borrowings,total_assets,debt_to_equity,equity_ratio,company_name,sector
0,NTPC,TTM,185892,22546,Sep 2024,9697.0,158575,242009,492230,0,0,NTPC,Energy
1,ONGC,TTM,658694,42320,Sep 2024,6290.0,345986,191489,757614,0,0,ONGC,Energy
2,ABB,TTM,6066,1285,Sep 2024,21.0,3500,60,5063,0,0,ABB India,Industrial
3,POWERGRID,TTM,45812,15712,Sep 2024,9301.0,82760,122568,255297,0,0,Power Grid,Energy
4,RELIANCE,TTM,939838,79941,Sep 2024,6766.0,812687,357525,1815123,0,0,Reliance Industries,Energy

In [6]:
features = peer_df[
    [
        "sales",
        "net_profit",
        "equity_ratio",
        "debt_to_equity"
    ]
]

In [7]:
scaler = StandardScaler()

scaled = scaler.fit_transform(features)

In [8]:
similarity_matrix = cosine_similarity(
    scaled
)

In [9]:
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=peer_df["symbol"],
    columns=peer_df["symbol"]
)

similarity_df.head()

symbol,NTPC,ONGC,ABB,POWERGRID,RELIANCE,ASIANPAINT,NESTLEIND,MARUTI,WIPRO,TECHM,...,ICICIBANK,BHARTIARTL,HCLTECH,LT,KOTAKBANK,ULTRACEMCO,ADANIPORTS,JSWSTEEL,SUNPHARMA,ADANIENT
symbol,,,,,,,,,,,,,,,,,,,,,
NTPC,1.000000,0.872116,-0.998652,-0.878223,0.965150,-0.998713,-0.998004,-0.972512,-0.992117,-0.999347,...,0.796552,-0.935746,-0.956294,-0.088310,-0.546682,-0.999127,-0.969041,-0.822056,-0.973034,-0.981161
ONGC,0.872116,1.000000,-0.896336,-0.999920,0.969771,-0.895814,-0.901278,-0.734209,-0.926557,-0.853868,...,0.398870,-0.643515,-0.977074,0.410371,-0.886480,-0.850911,-0.965924,-0.438318,-0.961461,-0.761159
ABB,-0.998652,-0.896336,1.000000,0.901861,-0.977432,0.999999,0.999936,0.959116,0.997284,0.996125,...,-0.764099,0.916180,0.970182,0.036491,0.589406,0.995612,0.980550,0.791394,0.983694,0.969812
POWERGRID,-0.878223,-0.999920,0.901861,1.000000,-0.972774,0.901352,0.906675,0.742720,0.931231,0.860370,...,-0.410413,0.653125,0.979683,-0.398828,0.880568,0.857474,0.969114,0.449628,0.964855,0.769285
RELIANCE,0.965150,0.969771,-0.977432,-0.972774,1.000000,-0.977183,-0.979751,-0.877683,-0.990336,-0.955065,...,0.610578,-0.810841,-0.999489,0.175442,-0.746760,-0.953373,-0.999883,-0.644395,-0.999487,-0.896411

In [10]:
similar_peers = (
    similarity_df["TCS"]
    .sort_values(ascending=False)
    .head(10)
)

similar_peers

symbol
TCS           1.000000
HDFCBANK      0.999613
ICICIBANK     0.967175
NTPC          0.924033
INFY          0.842189
RELIANCE      0.791781
TATAMOTORS    0.641438
ONGC          0.618800
AXISBANK      0.405098
KOTAKBANK    -0.185028
Name: TCS, dtype: float64

In [11]:
similarity_df.to_csv(
    "peer_mapping.csv"
)

print("Peer Mapping Saved")

Peer Mapping Saved